/*
-- Query: SELECT * FROM myBookStoreDataBase.book
LIMIT 0, 1000

-- Date: 2021-06-13 12:41
*/
INSERT INTO `` (`id`,`author`,`description`,`image`,`inventory`,`isbn`,`name`,`price`,`type`) VALUES (1,'Liu Cixion','The Three-Body Problem is the first chance for English-speaking readers to experience the Hugo Award-winning phenomenon from China\'s most beloved science fiction author, Liu Cixin.  Set against the backdrop of China\'s Cultural Revolution, a secret military project sends signals into space to establish contact with aliens. An alien civilization on the brink of destruction captures the signal and plans to invade Earth. Meanwhile, on Earth, different camps start forming, planning to either welcome the superior beings and help them take over a world seen as corrupt, or to fight against the invasion. The result is a science fiction masterpiece of enormous scope and vision.','images/3bodyCoverSingle.jpeg',133,'978-7-18618-1','Three Body',2340,'novel');
INSERT INTO `` (`id`,`author`,`description`,`image`,`inventory`,`isbn`,`name`,`price`,`type`) VALUES (2,'JK Rowling','Now for the first time ever, J.K. Rowling’s seven bestselling Harry Potter books are available in a stunning\n                  paperback boxed set! The Harry Potter series has been hailed as “one for the ages” by Stephen King and “a\n                  spellbinding saga’ by USA Today. And most recently, The New York Times called Harry Potter and the Deathly\n                  Hallows the “fastest selling book in history.” This is the ultimate Harry Potter collection for Harry Potter\n                  fans of all ages!','images/harryCoverSingle.jpeg',123,'978-7-18618-2','Harry Potter',1300,'novel');
INSERT INTO `` (`id`,`author`,`description`,`image`,`inventory`,`isbn`,`name`,`price`,`type`) VALUES (3,'Walter Isaacson','Steven Paul Jobs (/dʒɒbz/; February 24, 1955 – October 5, 2011) was an American business magnate, industrial designer, investor, and media proprietor. He was the chairman, chief executive officer (CEO), and co-founder of Apple Inc.; the chairman and majority shareholder of Pixar; a member of The Walt Disney Company\'s board of directors following its acquisition of Pixar; and the founder, chairman, and CEO of NeXT. Jobs is widely recognized as a pioneer of the personal computer revolution of the 1970s and 1980s, along with his early business partner and fellow Apple co-founder Steve Wozniak.\n\nJobs was born in San Francisco, California, and put up for adoption. He was raised in the San Francisco Bay Area. He attended Reed College in 1972 before dropping out that same year, and traveled through India in 1974 seeking enlightenment and studying Zen Buddhism.\n\nJobs and Wozniak co-founded Apple in 1976 to sell Wozniak\'s Apple I personal computer. Together the duo gained fame and wealth a year later with the Apple II, one of the first highly successful mass-produced microcomputers. Jobs saw the commercial potential of the Xerox Alto in 1979, which was mouse-driven and had a graphical user interface (GUI). This led to the development of the unsuccessful Apple Lisa in 1983, followed by the breakthrough Macintosh in 1984, the first mass-produced computer with a GUI. The Macintosh introduced the desktop publishing industry in 1985 with the addition of the Apple LaserWriter, the first laser printer to feature vector graphics. Jobs was forced out of Apple in 1985 after a long power struggle with the company\'s board and its then-CEO John Sculley. That same year, Jobs took a few of Apple\'s members with him to found NeXT, a computer platform development company that specialized in computers for higher-education and business markets. In addition, he helped to develop the visual effects industry when he funded the computer graphics division of George Lucas\'s Lucasfilm in 1986. The new company was Pixar, which produced the first 3D computer animated feature film Toy Story (1995), and went on to become a major animation studio, producing over 20 films since then.','images/JobsCover.jpeg',432,'978-7-18618-3','Steve Jobs',2200,'biographies');
INSERT INTO `` (`id`,`author`,`description`,`image`,`inventory`,`isbn`,`name`,`price`,`type`) VALUES (4,' Ashlee Vance','Elon Reeve Musk FRS (/ˈiːlɒn/ EE-lon; born June 28, 1971) is an entrepreneur and business magnate. He is the founder, CEO, and chief engineer at SpaceX; early stage investor,[note 1] CEO, and product architect of Tesla, Inc.; founder of The Boring Company; and co-founder of Neuralink and OpenAI. A centibillionaire, Musk is one of the richest people in the world.\n\nMusk was born to a Canadian mother and South African father and raised in Pretoria, South Africa. He briefly attended the University of Pretoria before moving to Canada aged 17 to attend Queen\'s University. He transferred to the University of Pennsylvania two years later, where he received bachelor\'s degrees in economics and physics. He moved to California in 1995 to attend Stanford University but decided instead to pursue a business career, co-founding the web software company Zip2 with his brother Kimbal. The startup was acquired by Compaq for $307 million in 1999. Musk co-founded online bank X.com that same year, which merged with Confinity in 2000 to form PayPal. The company was bought by eBay in 2002 for $1.5 billion.','images/MuskCover.jpeg',1234,'978-7-18618-4','Elon Musk',3299,'biographies');
